services:
  pgsql:
    image: postgres:14-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - lovelace-network

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      pgsql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - lovelace-network
  
  ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    entrypoint: ./entrypoint.sh
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - lovelace-network

volumes:
  pgdata:
networks:
  lovelace-network: