services:
  pgsql:
    image: postgres:14-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - lovelace-network

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "89:80"
    networks:
      - lovelace-network
    attach: false # Hides bloat from pgadmin on console

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    volumes:
      - ./api/lovelace:/app/lovelace
      - ./api/migrations:/app/migrations
      - ./api/scripts:/app/scripts
      - ./api/tests:/app/tests
    depends_on:
      pgsql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - lovelace-network

  ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    entrypoint: ./entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public
    env_file:
      - .env
    networks:
      - lovelace-network

volumes:
  pgdata:
networks:
  lovelace-network: