services:
  pgsql:
    image: postgres:14-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    networks:
      - lovelace-network

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "89:80"
    networks:
      - lovelace-network

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    depends_on:
      pgsql:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - lovelace-network

  ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    entrypoint: ./entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public
    env_file:
      - .env
    networks:
      - lovelace-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - lovelace-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    
  worker:
    build:
      context: .
      dockerfile: ./system/Dockerfile
    volumes:
      - ./system:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - worker-code:/app/code
    networks:
      - lovelace-network

volumes:
  pgdata:
  rabbitmq-data:
  rabbitmq-log:
  worker-code:
networks:
  lovelace-network:
