"""add role to user model

Revision ID: 6f5c0743ca88
Revises: 2a6f3cdb91d0
Create Date: 2024-07-12 14:14:38.691792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f5c0743ca88'
down_revision: Union[str, None] = '2a6f3cdb91d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('role', sa.Enum('admin', 'user', name='role'), nullable=False))
    # op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('users', 'is_active')
    # op.drop_column('users', 'role')
    # ### end Alembic commands ###
