"""update mvp models

Revision ID: 9c86e83d6b99
Revises: f66224a3166a
Create Date: 2024-10-24 17:09:04.172861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c86e83d6b99'
down_revision: Union[str, None] = 'f66224a3166a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('input', sa.String(), nullable=False),
    sa.Column('output', sa.String(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('problems', sa.Column('time_limit', sa.Integer(), nullable=False))
    op.add_column('problems', sa.Column('memory_limit', sa.Integer(), nullable=False))
    op.drop_column('problems', 'status')
    op.create_foreign_key(None, 'problems_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'problems_tags', 'problems', ['problem_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems_tags', type_='foreignkey')
    op.drop_constraint(None, 'problems_tags', type_='foreignkey')
    op.add_column('problems', sa.Column('status', postgresql.ENUM('todo', 'correct', 'wrong', name='problemstatus'), server_default=sa.text("'todo'::problemstatus"), autoincrement=False, nullable=False))
    op.drop_column('problems', 'memory_limit')
    op.drop_column('problems', 'time_limit')
    op.drop_table('test_cases')
    # ### end Alembic commands ###
