"""fix submissionstatus

Revision ID: c44ade0cf445
Revises: 9c86e83d6b99
Create Date: 2024-10-27 17:50:50.108079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c44ade0cf445'
down_revision: Union[str, None] = '9c86e83d6b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Reference: https://stackoverflow.com/questions/14845203/altering-an-enum-field-using-alembic

old_enum = postgresql.ENUM('wrong_answer', 'accepted', 'compilation_error', 'runtime_error', 'time_limit_exceeded', 'presentation_error', 'pending', 'testing', 'memory_limit_exceeded', 'server_error', name='submissonstatus')
new_enum = postgresql.ENUM('wrong_answer', 'accepted', 'compilation_error', 'runtime_error', 'time_limit_exceeded', 'presentation_error', 'pending', 'running', 'memory_limit_exceeded', 'server_error', name='submissonstatus')
tmp_enum = postgresql.ENUM('wrong_answer', 'accepted', 'compilation_error', 'runtime_error', 'time_limit_exceeded', 'presentation_error', 'pending', 'running', 'memory_limit_exceeded', 'server_error', name='_submissonstatus')

tcr = sa.sql.table('submissions',
                   sa.Column('status', new_enum, nullable=False))

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tmp_enum.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE submissions ALTER COLUMN status TYPE _submissonstatus'
               ' USING status::text::_submissonstatus')
    old_enum.drop(op.get_bind(), checkfirst=False)

    new_enum.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE submissions ALTER COLUMN status TYPE submissonstatus'
               ' USING status::text::submissonstatus')
    
    tmp_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(tcr.update().where(tcr.c.status==u'running')
               .values(status='server_error'))
    
    tmp_enum.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE submissions ALTER COLUMN status TYPE _submissonstatus'
               ' USING status::text::_submissonstatus')
    new_enum.drop(op.get_bind(), checkfirst=False)

    old_enum.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE submissions ALTER COLUMN status TYPE submissonstatus'
               ' USING status::text::submissonstatus')
    tmp_enum.drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
