"""Created new classes and minor fixes

Revision ID: f5cb0c2f2427
Revises: c44ade0cf445
Create Date: 2024-11-05 19:05:17.130034

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5cb0c2f2427'
down_revision: Union[str, None] = 'c44ade0cf445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

old_enum = postgresql.ENUM('wrong_answer', 'accepted', 'compilation_error', 'runtime_error', 'time_limit_exceeded', 'presentation_error', 'pending', 'running', 'memory_limit_exceeded', 'server_error', name='submissonstatus')
new_enum = postgresql.ENUM('wrong_answer', 'accepted', 'compilation_error', 'runtime_error', 'time_limit_exceeded', 'presentation_error', 'pending', 'running', 'memory_limit_exceeded', 'server_error', name='submissionstatus')

tcr = sa.sql.table('submissions',
                   sa.Column('status', new_enum, nullable=False))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    problemstatus = postgresql.ENUM('todo', 'correct', 'wrong', name='problemstatus', create_type=False)
    problemstatus.create(op.get_bind(), checkfirst=True)
    op.create_table('problems_user_status',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('status', problemstatus, server_default='todo'),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'problem_id')
    )
    op.add_column('problems', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('problems', sa.Column('author_id', sa.Integer(), nullable=True))
    op.execute('UPDATE problems SET author_id = 1 WHERE author_id IS NULL')
    op.alter_column('problems', 'author_id', existing_type=sa.Integer(), nullable=False)
    op.create_foreign_key(None, 'problems', 'users', ['author_id'], ['id'])
    new_enum.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE submissions ALTER COLUMN status TYPE submissionstatus'
               ' USING status::text::submissionstatus')
    old_enum.drop(op.get_bind(), checkfirst=False)



def downgrade() -> None:
    old_enum.create(op.get_bind(), checkfirst=False)
    op.execute('ALTER TABLE submissions ALTER COLUMN status TYPE submissonstatus'
               ' USING status::text::submissonstatus')
    new_enum.drop(op.get_bind(), checkfirst=False)
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.drop_column('problems', 'author_id')
    op.drop_column('problems', 'created_at')
    op.drop_table('problems_user_status')
    # ### end Alembic commands ###
