"""rollback on problemstatus table

Revision ID: fcfd0f70e1f8
Revises: f5cb0c2f2427
Create Date: 2024-11-06 13:35:15.752011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcfd0f70e1f8'
down_revision: Union[str, None] = 'f5cb0c2f2427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problems_user_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems_user_status',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('todo', 'correct', 'wrong', name='problemstatus'), server_default=sa.text("'todo'::problemstatus"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name='problems_user_status_problem_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='problems_user_status_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'problem_id', name='problems_user_status_pkey')
    )
    # ### end Alembic commands ###
