FROM node:20-alpine AS builder

WORKDIR /app

COPY /ui/package.json /ui/package-lock.json ./

RUN npm ci --production

COPY /ui .

RUN ["npm", "run", "build"]


FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 3000

CMD ["npm", "start"]
