name: Continuos Integration

on:
  pull_request:
    branches: ["main", "development"]

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.
      - name: run install and lint
        working-directory: ./ui
        run: |
          npm install
          npm run lint
